In [ ]:
# pip install cmake
# pip install dlib
# pip install face_recognition
# pip install opencv-python

In [3]:
import cv2  #OpenCV
import face_recognition as fc  #Facerecognition Library

In [43]:
image1 = fc.load_image_file('images/BarackObama1.jpg')
print(image1)
print(type(image1))

[[[ 92  34  30]
  [ 89  31  27]
  [ 85  27  23]
  ...
  [114  41  35]
  [119  44  39]
  [126  51  46]]

 [[ 92  34  30]
  [ 88  30  26]
  [ 84  26  22]
  ...
  [115  42  36]
  [121  46  41]
  [127  52  47]]

 [[ 93  36  29]
  [ 87  30  23]
  [ 82  25  18]
  ...
  [115  42  36]
  [120  45  40]
  [126  51  46]]

 ...

 [[185 160 156]
  [191 166 162]
  [196 172 168]
  ...
  [135 137 134]
  [125 127 126]
  [116 118 117]]

 [[184 150 148]
  [188 157 154]
  [194 165 161]
  ...
  [125 127 122]
  [111 113 110]
  [100 102  99]]

 [[185 147 146]
  [189 154 152]
  [193 162 159]
  ...
  [113 115 110]
  [ 99 101  98]
  [ 87  89  86]]]
<class 'numpy.ndarray'>


In [44]:
cv2.imshow('Barack', image1)

cv2.waitKey()
cv2.destroyAllWindows()

In [47]:
image2 = fc.load_image_file('images/BarackObama2.jpg')
print(image1)
print(type(image1))

[[[ 92  34  30]
  [ 89  31  27]
  [ 85  27  23]
  ...
  [114  41  35]
  [119  44  39]
  [126  51  46]]

 [[ 92  34  30]
  [ 88  30  26]
  [ 84  26  22]
  ...
  [115  42  36]
  [121  46  41]
  [127  52  47]]

 [[ 93  36  29]
  [ 87  30  23]
  [ 82  25  18]
  ...
  [115  42  36]
  [120  45  40]
  [126  51  46]]

 ...

 [[185 160 156]
  [191 166 162]
  [196 172 168]
  ...
  [135 137 134]
  [125 127 126]
  [116 118 117]]

 [[184 150 148]
  [188 157 154]
  [194 165 161]
  ...
  [125 127 122]
  [111 113 110]
  [100 102  99]]

 [[185 147 146]
  [189 154 152]
  [193 162 159]
  ...
  [113 115 110]
  [ 99 101  98]
  [ 87  89  86]]]
<class 'numpy.ndarray'>


In [48]:
cv2.imshow('Steve Jobs', image2)

cv2.waitKey()
cv2.destroyAllWindows()

In [49]:
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)
cv2.imshow('Barack', image1)

image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
cv2.imshow('Barack', image2)

cv2.waitKey()
cv2.destroyAllWindows()


In [50]:
face_location1 = fc.face_locations(image1)[0]
print(face_location1)

(170, 740, 491, 419)


In [51]:
face_location2 = fc.face_locations(image2)[0]
print(face_location2)

(56, 354, 163, 247)


In [52]:
image1_x1y1 = (face_location1[3], face_location1[0])
image1_x2y2 = (face_location1[1], face_location1[2])

print(image1_x1y1)
print(image1_x2y2)

(419, 170)
(740, 491)


In [53]:
image2_x1y1 = (face_location2[3], face_location2[0])
image2_x2y2 = (face_location2[1], face_location2[2])

print(image2_x1y1)
print(image2_x2y2)

(247, 56)
(354, 163)


In [54]:
encoding1 = fc.face_encodings(image1)[0]
print(encoding1)

[-0.07836477  0.07059104  0.03503565 -0.07424261 -0.00702395  0.00250947
 -0.0528708  -0.08785082  0.1989921  -0.11086334  0.23935452  0.09204039
 -0.21912459 -0.13326204  0.07117756  0.08879444 -0.16583574 -0.05121604
 -0.11221389 -0.10487619  0.03708556  0.00681212  0.13472176 -0.01124198
 -0.10822314 -0.35323253 -0.07173001 -0.15536651  0.02650305 -0.11373363
 -0.05930553  0.01738847 -0.18361245 -0.10362038 -0.0094263  -0.04247082
 -0.0346983  -0.03777081  0.2559599   0.02249065 -0.11669662  0.06066357
  0.02336948  0.17186734  0.29884186  0.05019968 -0.01521817 -0.08056507
  0.12318266 -0.26659271  0.07480796  0.14080548  0.08514915  0.06062996
  0.08915518 -0.16081817  0.01627879  0.07990666 -0.17684299  0.02911123
  0.02120306 -0.10716207 -0.07067432  0.04202493  0.20221545  0.13721247
 -0.09750096 -0.09333619  0.11980648 -0.06884895 -0.00213429  0.04446752
 -0.18342134 -0.18756396 -0.22649312  0.06083128  0.30475792  0.18197857
 -0.18052047  0.01326473 -0.20334859  0.01725238  0

In [55]:
encoding2 = fc.face_encodings(image2)[0]
print(encoding2)

[-0.07050529  0.17660645  0.04238453 -0.02506509 -0.04612515  0.01927942
 -0.07294136 -0.01918561  0.18185015 -0.07649928  0.2516914   0.08684783
 -0.26508188 -0.08788755  0.14593136  0.10183485 -0.24125986 -0.0760298
 -0.15189445 -0.0467329   0.00467781  0.04675081  0.02918064  0.00170951
 -0.14671491 -0.33737186 -0.0741742  -0.14359774  0.03074225 -0.1126752
 -0.0151473  -0.10023655 -0.17896989 -0.12990233  0.01984977 -0.03505253
 -0.08334775 -0.05482773  0.12578541  0.03235101 -0.14520302  0.04643627
  0.03179172  0.25282165  0.23355137  0.06717203  0.03641672 -0.06447294
  0.08326177 -0.29681054  0.09482213  0.16569018  0.11773758  0.08447208
  0.15644166 -0.14018203  0.02594629  0.17148665 -0.20040748  0.08606169
  0.11651418  0.01575623 -0.03270756  0.04092723  0.16877493  0.09660861
 -0.11236442 -0.11626028  0.11366075 -0.09344783 -0.07206983  0.0585131
 -0.12609045 -0.24489899 -0.28131431  0.07643466  0.33262253  0.17652409
 -0.1771773  -0.04741618 -0.10393716 -0.01921829  0.01

In [56]:
cv2.rectangle(image1, image1_x1y1, image1_x2y2, (255, 0, 255), 2)
cv2.rectangle(image2, image2_x1y1, image2_x2y2, (255, 0, 255), 2)

array([[[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       [[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       [[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       ...,

       [[19, 10,  6],
        [19, 10,  6],
        [20, 11,  8],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]],

       [[18,  9,  5],
        [18,  9,  5],
        [19, 10,  7],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]],

       [[18,  9,  5],
        [18,  9,  5],
        [18,  9,  6],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]]], dtype=uint8)

In [57]:
cv2.imshow('Barack', image2)
cv2.waitKey()
cv2.destroyAllWindows()

In [58]:
result = fc.compare_faces([encoding1], encoding2)
print(result)

[True]


In [59]:
if(result[0] == False):
    result = 'Person is Different'
else:
    result = 'Person is Same'

cv2.putText(image2, f'{result}', (30, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 255), 2)

array([[[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       [[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       [[16,  6,  6],
        [16,  6,  6],
        [16,  6,  6],
        ...,
        [18,  9,  6],
        [18,  9,  6],
        [18,  9,  6]],

       ...,

       [[19, 10,  6],
        [19, 10,  6],
        [20, 11,  8],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]],

       [[18,  9,  5],
        [18,  9,  5],
        [19, 10,  7],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]],

       [[18,  9,  5],
        [18,  9,  5],
        [18,  9,  6],
        ...,
        [25, 14, 16],
        [25, 14, 16],
        [26, 15, 17]]], dtype=uint8)

In [60]:

cv2.imshow('Barack Obama', image1)
cv2.imshow('Steve Jobs', image2)
cv2.waitKey()
cv2.destroyAllWindows()